### ISSUE TITLE
error: no matching constructor for initialization of 'amd_vi::DeviceID'

### ISSUE THREAD

**Issue by leap0x7b** [thomtl/Luna#1]
```
In file included from ../../kernel/source/drivers/iommu/amd/amd_vi.cpp:1:
In file included from ../../kernel/include/Luna/drivers/iommu/amd/amd_vi.hpp:5:
In file included from ../../kernel/include/Luna/cpu/cpu.hpp:6:
In file included from ../../kernel/include/Luna/cpu/threads.hpp:4:
In file included from ../../kernel/include/Luna/cpu/stack.hpp:4:
In file included from ../../kernel/include/Luna/mm/hmm.hpp:4:
In file included from ../../kernel/include/Luna/mm/pmm.hpp:4:
In file included from ../../kernel/include/Luna/misc/stivale2.hpp:6:
../../kernel/include/std/utility.hpp:29:69: error: no matching constructor for initialization of 'amd_vi::DeviceID'
        constexpr pair(U1&& x, U2&& y): first(std::forward<U1>(x)), second(std::forward<U2>(y)) {}
                                                                    ^      ~~~~~~~~~~~~~~~~~~~
```

**Comment by thomtl** [comment]
Please compile using GCC 10.2.0

**Comment by leap0x7b** [comment]
I'm using clang

**Comment by thomtl** [comment]
I saw that in the discord, compilation using clang is not supported, please compile using GCC 10.2.0 or GCC 11.2.0
